import type { Metadata } from "next"
import localFont from "next/font/local"
import Image from "next/image"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div id="root" className="w-full h-full fixed">
          <Image
            className="object-cover w-full h-full brightness-90 fixed"
            src={"/strive-background.png"}
            alt="Website background image"
            width={1920}
            height={1080}
            priority={true}
          />
          <div className="flex justify-center items-center flex-col relative">
            <Image
              src={`/logo.png`}
              alt="Website logo"
              width={1394}
              height={329}
              className="w-64"
            />
            <div>Test your Guilty Gear knowledge</div>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
